travis:
  secure:
    BINSTAR_TOKEN: vf7Bnj9AZ2x4RW13cLzI77Aio+HUj2xl/Nulcn/LVTe9oRaHIQkZv5fuxz/hvnAvBH96n5ywymxFKnDN7TD952UCPx/F5NqZspFcoI8MP1yYX6Zmz4tLJU3OApe+NrgKDDcBYbL8xsdoUz6VVicx/mv23lp+Uu+ooKhnlceyg+MpjEe7PLUTkIPBgKz7Qkb+eZjGxmW2tmcqxgTy3tTpnhLWMXe8t8NVUJumyjzgEv5Spppt/xoEQHncrfWvqCHkHmP1Cb9YdFEOq13fj6iOfXjFxlerI9ksaMjussFw/RfyKRXy9Ow6jRQSVSl5lrcNh4pdxExSrEFmh2O+IDNE/pghnTjjwWcpREZr5+U8XWbJalm3fcLCfdAuxQAqETMh4pJ03YJ8YQS5ugbuVWrQkWDUR7w4REVvt2/RsxtJNBo5zt+uyaHR7OBEc1Qe/JiXTy2EY0S8G9lVptvFvdokrrDIw53aiLUpaALoNmdkJ7eBtrgvlktdmNT/ljsn1PF9+Zdk0ZOTZ4vrqhdem7g5d8xMtX/GeD4mKd5gSKWYuxBz91iJRRkdFdx7BsffV6z+6JRRv0ZMOVv2JuQle7ZQam8JV7Gb9MsOIEJSBVky5R91qIJRD19cIFPUHEuHWY6tOQMMqsT8uxtDC6rt9Eq5XvbsqzZ3gnMcR+IsQrpdUbg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
