travis:
  secure:
    BINSTAR_TOKEN: iq7JWS2oLOCdxr2ldrNZl7p1unVLi1Zvy/R762gmsrsevzgmJgCZhNoJXzAKIHoTaYwYJrnxBCP7dg7KHUyoJdUleDv5frm9kdc6jPf7wFxFFPea+Tl+gNIKG0MBxkagFxLpcxHxQ/8EhdvddF3MXF/KyfM3WF8z4JO3cXuVk3Ulh87dixAh4VgtlSILOZ4jcE7nF/yGRaBs8cu1cslxt3+pYUVnc8bilU1GSFGIyc77YnBza+NK3/KHNFrwhqfaHFxqVlOx1B147RQaAbtttDwMMajsxw54HTYQdeLWALKLNe7FeGVG3cKKYAZwOwyj2e3NNN6R+rtnO/cpafwZPtmDAa6bjiwUIxvKsjvcbJMsJPAUZrYGyoSaBbgXhDdQG7/8M7HWgNf3ujH7ag1xV2m4G1ebodZJo+nsNYaVR2jQAD7/roQmo2neJxWPa7y48nmm3BHOQnqIyRC7U7L/O+/xeQcNeeRv7ZIDMRA1CYd+/vmqXaXmf1GumOBanxLwuD8a5ef4q5hFqmsX9TE/jtlpoNzpZd8HXvi5X6Ek+KtnkPqNgyKESRGDCmud51RW9KlUd9HjUCbLkA1h3yhhOgHlmT56iN7dn2N2//qbo+BTZ67kRxpUh83ONjpfRL1I685nW7967IPKLHLOXOfZOcO3aLVRhO+QeeA3K4EaimE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
