appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: HfGedSr8Px9nKcclr6iACUoeYjgh4GPkuEfQrzuUCPbeNxjM/rlWk4bAtMGmMn7nCBcuzDYbgvpOS+bPhl7oNMOPeR1hx+iCiMGkq+V4eGQfFcYCoCEKeABohrSj3vh0TQUeOSUrA3CmDmkhGzlgWvJVbcD8OuUfaBvmw+yDPZS7bmJK+W3wG1yHilVcBN/+s+wBzxLA7PiebX0a1ihx49PoKOpNSxkdAEr8Xe2UDz/ZbBgeFVYSResHis3SvIe1Jo/oKQNZBFLRoL2DC407bWtUVR4lh47DWy2PAg7HtiV6KKPYd11iqCHDwWQV0tWivTt9/cn/tOs4l6Q5kG/tiHJZSPtDmPt3mjCZns0kG6vDo7Jx9b8pmM6IYnlFTMKLRBZBzPafxfsfHpnTHok+3nJRvy2CN+PJ8MlTpW5rvHhdY9CfxVwk0YRg3cShBK7r1EV4NLdZxwCitpMHPWrXxfPp2M08Djs2cTUS2dnHr3dxvGVo22w5YBhahYm7ZeVvBc8YBu+T1/CNLvHP5HNNQgf64E7iBJoxV9xPG8tMFXdutReRtQIopXwOmG5Wd80FITiUqPtBkCFt+dxXt36l5h2rxAAIEiFA0BUqueHRF9lqXMIi8SLpPOazng55+PnJ9uECa3YDjW3sdMMvQwbEV1nWprwKnhBcPd22/aiopWQ=
conda_forge_output_validation: true
