travis:
  secure:
    BINSTAR_TOKEN: VAnlTrizD+6kk/Y6Pdt58/vHt4ulwaxvAOWh2tAVHeIt3jVAkqBeqOAi8zRPRqrjyplvSEtK7NU+veR697LFjUar0CZxuixtA8VLyowvZgyp+SRTyJ1vWiJGtzmdJkDwlYJ9WH/6sGJvjmVum6zUKx/RehGQ40SfahcuU6IoHTNXKmiS+c8fk6zgLdnzVsmj3FfqYJUslVAdugaNVkQJq1fBvtpH1x3RKGkwlxU3BRr8zWYg7Y42GtrwTC355Nan4tCcfoHwI5HEKdwdn2jMr9ggrjBBQKPFvXCDPgS9RBWgk94zeXBSFfg39BFOcH1G+8ECmZsSK/4n1dyqmApTj3XwJNIivkg7J43y0jKXHd/f4FtKfVLsNhuehal/ItgliuZbz+KIvi2nF6y7Hnqwe6PC4n1+ZuaIabZPDGJ78HHHEvxK+fDNsx7VipQorjHY/m+Usd1Ympv3lmsF0hioe6PqwqjjQAycdxkIbCRCu7NQy62VjiAC0lBJpismSltG3FrWxEMlPqS2zMjmoxujFGpm9dk4mg9CizEUy1kMCvdO/XL4wPTSPOSmLRLpvSJrj6k2aD1s21eDg9jVzNKMjspFQikcqTpjBhr8SSHc3W9gt0NnrK799w8X/71iGKffn2Kevuw8Tg28/4nIu6/lKSrDJpzbuwkaDN+neVGvItc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
